/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meteo/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les lieux rapides proposés par l’application */
        get: operations["listWeatherLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meteo/essential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retourne les données nécessaires à la lecture météo essentielle */
        get: operations["getEssentialWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LocationSummary: {
            id: string;
            label: string;
            shortLabel: string;
            latitude: number;
            longitude: number;
        };
        LocationsResponse: {
            locations: components["schemas"]["LocationSummary"][];
        };
        /** @enum {string} */
        AlertLevel: "green" | "yellow" | "orange" | "red";
        Location: {
            id: string | null;
            label: string;
            latitude: number;
            longitude: number;
            altitudeM: number | null;
            accuracyM: number | null;
            /** @enum {string} */
            source: "preset" | "gps";
        };
        CurrentWeather: {
            temperatureC: number;
            apparentTemperatureC: number;
            weatherLabel: string;
            /** Format: date-time */
            observedAt: string;
            /** @enum {string} */
            nature: "observation" | "model";
            sourceLabel: string;
            stale: boolean;
        };
        DayRange: {
            minimumC: number;
            maximumC: number;
        };
        NextChange: {
            /** @enum {string} */
            type: "rain" | "wind" | "temperature" | "stable";
            /** Format: date-time */
            startsAt: string | null;
            summary: string;
            probabilityPercent: number | null;
        };
        HourForecast: {
            /** Format: date-time */
            at: string;
            temperatureC: number;
            rainProbabilityPercent: number;
            windGustKmh: number;
        };
        WeatherAlert: {
            level: components["schemas"]["AlertLevel"];
            title: string;
            phenomena: string[];
            /** Format: date-time */
            validUntil: string;
            /** Format: uri */
            sourceUrl: string;
        };
        EssentialWeather: {
            location: components["schemas"]["Location"];
            current: components["schemas"]["CurrentWeather"];
            today: components["schemas"]["DayRange"];
            nextChange: components["schemas"]["NextChange"];
            nextHours: components["schemas"]["HourForecast"][];
            alert: components["schemas"]["WeatherAlert"];
            unavailableSources: string[];
            /** Format: date-time */
            generatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listWeatherLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lieux disponibles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationsResponse"];
                };
            };
        };
    };
    getEssentialWeather: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                /** @description Précision fournie par le navigateur pour une position GPS. */
                accuracyM?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lecture météo normalisée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EssentialWeather"];
                };
            };
            /** @description Coordonnées invalides */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aucune donnée météo exploitable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
