import type { StationMeteo } from "@opendata-vda/shared/stations-meteo";
export const STATION_SELECTION_POLICY_VERSION = "1" as const;
export const STATION_SELECTION_POLICY = { maxDistanceKm: 50, maxDistanceWithoutAltitudeKm: 5, maxAltitudeDifferenceM: 500, maxAgeMinutes: 90, staleAfterMinutes: 60, futureToleranceMinutes: 15, maxScore: 60 } as const;
export interface StationMeasurement { station: StationMeteo; temperatureC: number; observedAt: string }
export interface StationDecision { status: "selected" | "no_measurements" | "no_eligible_station"; reasonCode: "BEST_ELIGIBLE_STATION" | "NO_VALID_MEASUREMENTS" | "NO_ELIGIBLE_STATION"; evaluatedCandidates: number; eligibleCandidates: number; selected: (StationMeasurement & { distanceKm: number; altitudeDifferenceM: number | null; ageMinutes: number; selectionScore: number; stale: boolean }) | null }
const round = (value: number) => Math.round(value * 10) / 10;
function distance(a: { latitude: number; longitude: number }, b: StationMeteo) { const r = Math.PI / 180, p = Math.sin((b.lat - a.latitude) * r / 2) ** 2 + Math.cos(a.latitude * r) * Math.cos(b.lat * r) * Math.sin((b.lon - a.longitude) * r / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(p), Math.sqrt(1 - Math.min(1, p))); }
export function selectStationObservation(target: { latitude: number; longitude: number; altitudeM: number | null }, measurements: readonly StationMeasurement[], now = new Date()): StationDecision {
  const candidates = measurements.flatMap((measurement) => { const observed = Date.parse(measurement.observedAt), d = distance(target, measurement.station), age = (now.getTime() - observed) / 60000, altitudeDifferenceM = target.altitudeM === null ? null : Math.abs(target.altitudeM - measurement.station.altitudeM); const valid = Number.isFinite(measurement.temperatureC) && measurement.temperatureC >= -60 && measurement.temperatureC <= 60 && Number.isFinite(observed); if (!valid || d > 50 || (target.altitudeM === null && d > 5) || (altitudeDifferenceM !== null && altitudeDifferenceM > 500) || age > 90 || age < -15) return []; const score = d / 50 * 50 + (altitudeDifferenceM === null ? 8 : altitudeDifferenceM / 500 * 30) + Math.max(0, age) / 90 * 20 + (measurement.station.reseau === "infoclimat" ? 5 : 0); if (score > 60) return []; return [{ ...measurement, distanceKm: round(d), altitudeDifferenceM, ageMinutes: round(Math.max(0, age)), selectionScore: round(score), stale: age > 60 }]; });
  candidates.sort((a, b) => a.selectionScore - b.selectionScore || Number(a.station.reseau === "infoclimat") - Number(b.station.reseau === "infoclimat") || a.distanceKm - b.distanceKm || a.station.id.localeCompare(b.station.id)); const selected = candidates[0] ?? null; return { status: selected ? "selected" : measurements.length === 0 ? "no_measurements" : "no_eligible_station", reasonCode: selected ? "BEST_ELIGIBLE_STATION" : measurements.length === 0 ? "NO_VALID_MEASUREMENTS" : "NO_ELIGIBLE_STATION", evaluatedCandidates: measurements.filter((m) => Number.isFinite(m.temperatureC) && Number.isFinite(Date.parse(m.observedAt))).length, eligibleCandidates: candidates.length, selected };
}
